### ISSUE TITLE
Kafkat commands cause errors/exception in ZooKeeper.

### ISSUE THREAD

**Issue by aabouzaid** [airbnb/kafkat#26]
Hello,

Any command is done with `kafkat` causes errors/exception in ZooKeeper logs. e.g.
```
kafkat partitions
```

Causes in ZK logs:
```
2017-01-10 15:46:20,636 [myid:1] - WARN  [NIOServerCxn.Factory:/10.0.0.1:2181:NIOServerCnxn@357] - caught end of stream exception
EndOfStreamException: Unable to read additional data from client sessionid 0x158abc892551348, likely client has closed socket
	at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:228)
	at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:208)
	at java.lang.Thread.run(Thread.java:745)
2017-01-10 15:46:20,636 [myid:1] - INFO  [NIOServerCxn.Factory:/10.0.0.1:2181:NIOServerCnxn@1007] - Closed socket connection for client /10.0.0.4:37103 which had sessionid 0x158abc892551348
2017-01-10 15:46:20,646 [myid:1] - ERROR [CommitProcessor:1:NIOServerCnxn@178] - Unexpected Exception: 
java.nio.channels.CancelledKeyException
	at sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:73)
	at sun.nio.ch.SelectionKeyImpl.interestOps(SelectionKeyImpl.java:77)
	at org.apache.zookeeper.server.NIOServerCnxn.sendBuffer(NIOServerCnxn.java:151)
	at org.apache.zookeeper.server.NIOServerCnxn.sendResponse(NIOServerCnxn.java:1081)
	at org.apache.zookeeper.server.FinalRequestProcessor.processRequest(FinalRequestProcessor.java:404)
	at org.apache.zookeeper.server.quorum.CommitProcessor.run(CommitProcessor.java:74)
```
Nodes:
>10.0.0.1 => zk node.
10.0.0.4 => kafka/kafkat node.

Versions:
> Kafkat (0.3.0)
ZooKeeper (3.4.6)
Kafka (0.10.0.0)

**Comment by divyum** [comment]
@AAbouZaid  I checked with ZooKeeper (3.4.9) and Kafka (0.10.0.0), works fine for me.

**Comment by josephmc5** [comment]
I am getting the same thing

```2018-06-06 11:14:30,748 [myid:1] - ERROR [CommitProcessor:1:NIOServerCnxn@180] - Unexpected Exception:
java.nio.channels.CancelledKeyException
	at sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:73)
	at sun.nio.ch.SelectionKeyImpl.interestOps(SelectionKeyImpl.java:77)
	at org.apache.zookeeper.server.NIOServerCnxn.sendBuffer(NIOServerCnxn.java:153)
	at org.apache.zookeeper.server.NIOServerCnxn.sendResponse(NIOServerCnxn.java:1076)
	at org.apache.zookeeper.server.FinalRequestProcessor.processRequest(FinalRequestProcessor.java:404)
	at org.apache.zookeeper.server.quorum.CommitProcessor.run(CommitProcessor.java:74)
```

zookeeper 3.4.5
kafkat 0.3.0
kafka 0.10.1.1
